
#!/usr/bin/env python3
"""
Hybrid router: statute → Prolog → executor → label.
"""

import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, Tuple

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

from sara_hybrid.io.sara_loader import load_cases
from sara_hybrid.symbolic.executor import exec_rules

# -------------------- Translator --------------------
_MODEL_DIR = Path(__file__).resolve().parents[3] / "models" / "t5_statute2logic"
_TOKENIZER = AutoTokenizer.from_pretrained(str(_MODEL_DIR))
_MODEL     = AutoModelForSeq2SeqLM.from_pretrained(str(_MODEL_DIR)).eval()

def translate_statute_to_prolog(statute: str, max_new_tokens: int = 128) -> str:
    """Return Prolog code generated by fine-tuned Flan-T5."""
    inp = _TOKENIZER(statute, return_tensors="pt", truncation=True)
    out = _MODEL.generate(**inp, max_new_tokens=max_new_tokens)
    return _TOKENIZER.decode(out[0], skip_special_tokens=True).strip()

# -------------------- Fact extraction --------------------
_DOLLAR_RE = re.compile(r"\$([\d,]+)")

def facts_from_premise(premise: str) -> str:
    """
    Very naive: convert `$123,456` into fact `amount(123456).`
    Extend later as needed.
    """
    facts = []
    for amt in _DOLLAR_RE.findall(premise):
        num = amt.replace(",", "")
        facts.append(f"amount({num}).")
    return "\n".join(facts)

# -------------------- Router --------------------
ENTAILMENT = "Entailment"
CONTRADICTION = "Contradiction"
UNCLEAR = "unclear"

def decide_case(case: Dict) -> str:
    """
    case dict keys: 'statute', 'test case', 'answer', ...
    """
    rules = translate_statute_to_prolog(case["statute"])
    facts = facts_from_premise(case["test case"])

    is_entail, _ = exec_rules(rules, facts, "entailment.")
    if is_entail:
        return ENTAILMENT

    is_contra, _ = exec_rules(rules, facts, "contradiction.")
    if is_contra:
        return CONTRADICTION

    return UNCLEAR  # fallback path

def run_router(split: str = "test") -> None:
    cases = load_cases(split)
    counts = Counter()
    conf   = defaultdict(lambda: Counter())

    for c in cases:
        pred = decide_case(c)
        gold = ENTAILMENT if "Entail" in c["answer"] else CONTRADICTION
        counts[pred] += 1
        conf[gold][pred] += 1

    # simple metrics
    correct = sum(conf[g][g] for g in conf)
    acc = correct / len(cases)
    print(f"Evaluated {len(cases)} cases.  Accuracy: {acc:.3f}")
    print("Confusion matrix")
    for g in (ENTAILMENT, CONTRADICTION):
        row = conf[g]
        print(f"{g:14s}: ent {row[ENTAILMENT]:4d} | contra {row[CONTRADICTION]:4d} | unclear {row[UNCLEAR]:4d}")

if __name__ == "__main__":
    run_router("test")
